import { defineConfig } from "@pandacss/dev";

export default defineConfig({
   conditions: {
      light: "[data-color-mode=light] &",
      dark: "[data-color-mode=dark] &",
   },
   eject: true,
   exclude: [],
   include: ["./src/**/*.{js,jsx,ts,tsx}"],
   outdir: "styled-system",
   // Default patterns live here: https://github.com/chakra-ui/panda/blob/main/packages/preset-base/src/patterns.ts
   patterns: {
      extend: {
         box: {
            transform: (props) => {
               return props;
            },
         },
         flex: {
            properties: {
               align: { type: "property", value: "alignItems" },
               justify: { type: "property", value: "justifyContent" },
               direction: { type: "property", value: "flexDirection" },
               wrap: { type: "property", value: "flexWrap" },
               basis: { type: "property", value: "flexBasis" },
               grow: { type: "property", value: "flexGrow" },
               shrink: { type: "property", value: "flexShrink" },
            },
            transform(props) {
               const {
                  direction,
                  align,
                  justify,
                  wrap,
                  basis,
                  grow,
                  shrink,
                  ...rest
               } = props;
               return {
                  display: "flex",
                  flexDirection: direction,
                  alignItems: align,
                  justifyContent: justify,
                  flexWrap: wrap,
                  flexBasis: basis,
                  flexGrow: grow,
                  flexShrink: shrink,
                  ...rest,
               };
            },
         },
      },
   },
   preflight: true,
   presets: [],
   strictPropertyValues: true,
   strictTokens: true,
   
   theme: {
      tokens: {
         colors: {
            blue: {
               500: { value: "#2970FF" },
            },
         },
         radii: {
            "radius-none": { value: "0rem" },
            "radius-xxs": { value: "0.125rem" },
            "radius-xs": { value: "0.25rem" },
            "radius-sm": { value: "0.375rem" },
            "radius-md": { value: "0.5rem" },
            "radius-lg": { value: "0.625rem" },
            "radius-xl": { value: "0.75rem" },
            "radius-2xl": { value: "1rem" },
            "radius-3xl": { value: "1.25rem" },
            "radius-4xl": { value: "1.5rem" },
            "radius-full": { value: "9999px " },
         },
         spacing: {
            "0": { value: "0rem" },
            "spacing-none": { value: "0rem" },
            "0.5": { value: "0.125rem" },
            "spacing-xxs": { value: "0.125rem" },
            "1": { value: "0.25rem" },
            "spacing-xs": { value: "0.25rem" },
            "1.5": { value: "0.375rem" },
            "spacing-sm": { value: "0.375rem" },
            "2": { value: "0.5rem" },
            "spacing-md": { value: "0.5rem" },
            "3": { value: "0.75rem" },
            "spacing-lg": { value: "0.75rem" },
            "4": { value: "1rem" },
            "container-padding-mobile": { value: "1rem" },
            "spacing-xl": { value: "1rem" },
            "5": { value: "1.25rem" },
            "spacing-2xl": { value: "1.25rem" },
            "6": { value: "1.5rem" },
            "spacing-3xl": { value: "1.5rem" },
            "8": { value: "2rem" },
            "container-padding-desktop": { value: "2rem" },
            "spacing-4xl": { value: "2rem" },
            "10": { value: "2.5rem" },
            "spacing-5xl": { value: "2.5rem" },
            "12": { value: "3rem" },
            "spacing-6xl": { value: "3rem" },
            "16": { value: "4rem" },
            "spacing-7xl": { value: "4rem" },
            "20": { value: "5rem" },
            "spacing-8xl": { value: "5rem" },
            "24": { value: "6rem" },
            "spacing-9xl": { value: "6rem" },
            "32": { value: "8rem" },
            "spacing-10xl": { value: "8rem" },
            "40": { value: "10rem" },
            "spacing-11xl": { value: "10rem" },
            "48": { value: "12rem" },
            "spacing-12xl": { value: "12rem" },
            "56": { value: "14rem" },
            "spacing-13xl": { value: "14rem" },
            "64": { value: "16rem" },
            "spacing-14xl": { value: "16rem" },
            "80": { value: "20rem" },
            "spacing-15xl": { value: "20rem" },
            "width-xxs": { value: "20rem" },
            "96": { value: "24rem" },
            "spacing-16xl": { value: "24rem" },
            "width-xs": { value: "24rem" },
            "120": { value: "30rem" },
            "spacing-17xl": { value: "30rem" },
            "width-sm": { value: "30rem" },
            "140": { value: "35rem" },
            "spacing-18xl": { value: "35rem" },
            "width-md": { value: "35rem" },
            "160": { value: "40rem" },
            "spacing-19xl": { value: "40rem" },
            "width-lg": { value: "40rem" },
            "180": { value: "45rem" },
            "paragraph-max-width": { value: "45rem" },
            "spacing-20xl": { value: "45rem" },
            "192": { value: "48rem" },
            "spacing-21xl": { value: "48rem" },
            "width-xl": { value: "48rem" },
            "256": { value: "64rem" },
            "spacing-22xl": { value: "64rem" },
            "width-2xl": { value: "64rem" },
            "320": { value: "80rem" },
            "container-max-width-desktop": { value: "80rem" },
            "spacing-23xl": { value: "80rem" },
            "width-3xl": { value: "80rem" },
            "360": { value: "90rem" },
            "spacing-24xl": { value: "90rem" },
            "width-4xl": { value: "90rem" },
            "400": { value: "100rem" },
            "spacing-25xl": { value: "100rem" },
            "width-5xl": { value: "100rem" },
            "480": { value: "120 rem" },
            "spacing-26xl": { value: "120rem" },
            "width-6xl": { value: "120rem" },
         },
      },
   },

   // theme: {
   //    semanticTokens: {
   //       colors: {
   //          text: {
   //             value: {
   //                _pinkTheme: {
   //                   base: "{colors.pink.500}",
   //                   _dark: "{colors.pink.300}",
   //                },
   //                _blueTheme: {
   //                   base: "{colors.blue.500}",
   //                   _dark: "{colors.blue.300}",
   //                },
   //             },
   //          },
   //       },
   //    },
   // },
});
