/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeamsImport } from './routes/teams'
import { Route as IndexImport } from './routes/index'
import { Route as TeamIdImport } from './routes/team.$id'

// Create/Update Routes

const TeamsRoute = TeamsImport.update({
  path: '/teams',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamIdRoute = TeamIdImport.update({
  path: '/team/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/teams': {
      preLoaderRoute: typeof TeamsImport
      parentRoute: typeof rootRoute
    }
    '/team/$id': {
      preLoaderRoute: typeof TeamIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  TeamsRoute,
  TeamIdRoute,
])

/* prettier-ignore-end */
