/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as SubregionsImport } from './routes/subregions'
import { Route as PersonsImport } from './routes/persons'
import { Route as PersonGeneratorImport } from './routes/person-generator'
import { Route as CountriesImport } from './routes/countries'
import { Route as CitiesImport } from './routes/cities'
import { Route as IndexImport } from './routes/index'
import { Route as SubregionIdImport } from './routes/subregion.$id'
import { Route as PersonIdImport } from './routes/person.$id'
import { Route as CountryIdImport } from './routes/country.$id'
import { Route as CityIdImport } from './routes/city.$id'

// Create/Update Routes

const TestRoute = TestImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const SubregionsRoute = SubregionsImport.update({
  path: '/subregions',
  getParentRoute: () => rootRoute,
} as any)

const PersonsRoute = PersonsImport.update({
  path: '/persons',
  getParentRoute: () => rootRoute,
} as any)

const PersonGeneratorRoute = PersonGeneratorImport.update({
  path: '/person-generator',
  getParentRoute: () => rootRoute,
} as any)

const CountriesRoute = CountriesImport.update({
  path: '/countries',
  getParentRoute: () => rootRoute,
} as any)

const CitiesRoute = CitiesImport.update({
  path: '/cities',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SubregionIdRoute = SubregionIdImport.update({
  path: '/subregion/$id',
  getParentRoute: () => rootRoute,
} as any)

const PersonIdRoute = PersonIdImport.update({
  path: '/person/$id',
  getParentRoute: () => rootRoute,
} as any)

const CountryIdRoute = CountryIdImport.update({
  path: '/country/$id',
  getParentRoute: () => rootRoute,
} as any)

const CityIdRoute = CityIdImport.update({
  path: '/city/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cities': {
      preLoaderRoute: typeof CitiesImport
      parentRoute: typeof rootRoute
    }
    '/countries': {
      preLoaderRoute: typeof CountriesImport
      parentRoute: typeof rootRoute
    }
    '/person-generator': {
      preLoaderRoute: typeof PersonGeneratorImport
      parentRoute: typeof rootRoute
    }
    '/persons': {
      preLoaderRoute: typeof PersonsImport
      parentRoute: typeof rootRoute
    }
    '/subregions': {
      preLoaderRoute: typeof SubregionsImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/city/$id': {
      preLoaderRoute: typeof CityIdImport
      parentRoute: typeof rootRoute
    }
    '/country/$id': {
      preLoaderRoute: typeof CountryIdImport
      parentRoute: typeof rootRoute
    }
    '/person/$id': {
      preLoaderRoute: typeof PersonIdImport
      parentRoute: typeof rootRoute
    }
    '/subregion/$id': {
      preLoaderRoute: typeof SubregionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CitiesRoute,
  CountriesRoute,
  PersonGeneratorRoute,
  PersonsRoute,
  SubregionsRoute,
  TestRoute,
  CityIdRoute,
  CountryIdRoute,
  PersonIdRoute,
  SubregionIdRoute,
])

/* prettier-ignore-end */
